// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;  // Using Android configuration
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5HvWg6BjrBZeOzIRwGY01OA9V7ZtQhwM',
    appId: '1:766087143252:web:1cba7acc88926b4ec472c1',
    messagingSenderId: '766087143252',
    projectId: 'washmoose-app',
    authDomain: 'washmoose-app.firebaseapp.com',
    storageBucket: 'washmoose-app.firebasestorage.app',
  );

  // ✅ FIXED: Updated Android configuration with correct appId
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5lho_Xwe2YZKcCZLCyquFsXRZBQfFH8c',
    appId: '1:766087143252:android:6c9b400e0607e70ac472c1',  // ✅ FIXED: Correct appId
    messagingSenderId: '766087143252',
    projectId: 'washmoose-app',
    storageBucket: 'washmoose-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADjwi50yOauhC7Eo0UQwNyXLN6zZX3g7I',
    appId: '1:766087143252:ios:b63db9de298d2ee8c472c1',
    messagingSenderId: '766087143252',
    projectId: 'washmoose-app',
    storageBucket: 'washmoose-app.firebasestorage.app',
    iosBundleId: 'com.example.washmooseClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADjwi50yOauhC7Eo0UQwNyXLN6zZX3g7I',
    appId: '1:766087143252:ios:b63db9de298d2ee8c472c1',
    messagingSenderId: '766087143252',
    projectId: 'washmoose-app',
    storageBucket: 'washmoose-app.firebasestorage.app',
    iosBundleId: 'com.example.washmooseClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5HvWg6BjrBZeOzIRwGY01OA9V7ZtQhwM',
    appId: '1:766087143252:web:ad26410ff604e721c472c1',
    messagingSenderId: '766087143252',
    projectId: 'washmoose-app',
    authDomain: 'washmoose-app.firebaseapp.com',
    storageBucket: 'washmoose-app.firebasestorage.app',
  );
}